/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessoriesRouteImport } from './routes/accessories'
import { Route as AgeRestrictedRouteImport } from './routes/age-restricted'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as HookahRouteImport } from './routes/hookah'
import { Route as HouseOfRasaRouteImport } from './routes/house-of-rasa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsMajlisRouteImport } from './routes/collections.majlis'
import { Route as CollectionsMakhmalRouteImport } from './routes/collections.makhmal'
import { Route as CollectionsTarkibRouteImport } from './routes/collections.tarkib'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as ProductKeyRouteImport } from './routes/product.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessoriesRoute = AccessoriesRouteImport.update({
  id: '/accessories',
  path: '/accessories',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRestrictedRoute = AgeRestrictedRouteImport.update({
  id: '/age-restricted',
  path: '/age-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const HookahRoute = HookahRouteImport.update({
  id: '/hookah',
  path: '/hookah',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseOfRasaRoute = HouseOfRasaRouteImport.update({
  id: '/house-of-rasa',
  path: '/house-of-rasa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMajlisRoute = CollectionsMajlisRouteImport.update({
  id: '/collections/majlis',
  path: '/collections/majlis',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsMakhmalRoute = CollectionsMakhmalRouteImport.update({
  id: '/collections/makhmal',
  path: '/collections/makhmal',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsTarkibRoute = CollectionsTarkibRouteImport.update({
  id: '/collections/tarkib',
  path: '/collections/tarkib',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductKeyRoute = ProductKeyRouteImport.update({
  id: '/product/$key',
  path: '/product/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/partners': typeof PartnersRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$key': typeof ProductKeyRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/partners': typeof PartnersRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$key': typeof ProductKeyRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessories': typeof AccessoriesRoute
  '/age-restricted': typeof AgeRestrictedRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/coming-soon': typeof ComingSoonRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/hookah': typeof HookahRoute
  '/house-of-rasa': typeof HouseOfRasaRoute
  '/login': typeof LoginRoute
  '/loyalty': typeof LoyaltyRoute
  '/partners': typeof PartnersRoute
  '/shop': typeof ShopRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/settings': typeof AccountSettingsRoute
  '/collections/majlis': typeof CollectionsMajlisRoute
  '/collections/makhmal': typeof CollectionsMakhmalRoute
  '/collections/tarkib': typeof CollectionsTarkibRoute
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/product/$key': typeof ProductKeyRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/cart'
    | '/checkout'
    | '/coming-soon'
    | '/contact'
    | '/flavours'
    | '/hookah'
    | '/house-of-rasa'
    | '/login'
    | '/loyalty'
    | '/partners'
    | '/shop'
    | '/account/orders'
    | '/account/settings'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/order-confirmation/$orderId'
    | '/product/$key'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/cart'
    | '/checkout'
    | '/coming-soon'
    | '/contact'
    | '/flavours'
    | '/hookah'
    | '/house-of-rasa'
    | '/login'
    | '/loyalty'
    | '/partners'
    | '/shop'
    | '/account/orders'
    | '/account/settings'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/order-confirmation/$orderId'
    | '/product/$key'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/accessories'
    | '/age-restricted'
    | '/cart'
    | '/checkout'
    | '/coming-soon'
    | '/contact'
    | '/flavours'
    | '/hookah'
    | '/house-of-rasa'
    | '/login'
    | '/loyalty'
    | '/partners'
    | '/shop'
    | '/account/orders'
    | '/account/settings'
    | '/collections/majlis'
    | '/collections/makhmal'
    | '/collections/tarkib'
    | '/order-confirmation/$orderId'
    | '/product/$key'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessoriesRoute: typeof AccessoriesRoute
  AgeRestrictedRoute: typeof AgeRestrictedRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ContactRoute: typeof ContactRoute
  FlavoursRoute: typeof FlavoursRoute
  HookahRoute: typeof HookahRoute
  HouseOfRasaRoute: typeof HouseOfRasaRoute
  LoginRoute: typeof LoginRoute
  LoyaltyRoute: typeof LoyaltyRoute
  PartnersRoute: typeof PartnersRoute
  ShopRoute: typeof ShopRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  CollectionsMajlisRoute: typeof CollectionsMajlisRoute
  CollectionsMakhmalRoute: typeof CollectionsMakhmalRoute
  CollectionsTarkibRoute: typeof CollectionsTarkibRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
  ProductKeyRoute: typeof ProductKeyRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessories': {
      id: '/accessories'
      path: '/accessories'
      fullPath: '/accessories'
      preLoaderRoute: typeof AccessoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age-restricted': {
      id: '/age-restricted'
      path: '/age-restricted'
      fullPath: '/age-restricted'
      preLoaderRoute: typeof AgeRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hookah': {
      id: '/hookah'
      path: '/hookah'
      fullPath: '/hookah'
      preLoaderRoute: typeof HookahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-of-rasa': {
      id: '/house-of-rasa'
      path: '/house-of-rasa'
      fullPath: '/house-of-rasa'
      preLoaderRoute: typeof HouseOfRasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/majlis': {
      id: '/collections/majlis'
      path: '/collections/majlis'
      fullPath: '/collections/majlis'
      preLoaderRoute: typeof CollectionsMajlisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/makhmal': {
      id: '/collections/makhmal'
      path: '/collections/makhmal'
      fullPath: '/collections/makhmal'
      preLoaderRoute: typeof CollectionsMakhmalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/tarkib': {
      id: '/collections/tarkib'
      path: '/collections/tarkib'
      fullPath: '/collections/tarkib'
      preLoaderRoute: typeof CollectionsTarkibRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$key': {
      id: '/product/$key'
      path: '/product/$key'
      fullPath: '/product/$key'
      preLoaderRoute: typeof ProductKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessoriesRoute: AccessoriesRoute,
  AgeRestrictedRoute: AgeRestrictedRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ComingSoonRoute: ComingSoonRoute,
  ContactRoute: ContactRoute,
  FlavoursRoute: FlavoursRoute,
  HookahRoute: HookahRoute,
  HouseOfRasaRoute: HouseOfRasaRoute,
  LoginRoute: LoginRoute,
  LoyaltyRoute: LoyaltyRoute,
  PartnersRoute: PartnersRoute,
  ShopRoute: ShopRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  CollectionsMajlisRoute: CollectionsMajlisRoute,
  CollectionsMakhmalRoute: CollectionsMakhmalRoute,
  CollectionsTarkibRoute: CollectionsTarkibRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
  ProductKeyRoute: ProductKeyRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
